author: SwearWord
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: org.blockface.remotifier.Remotifier
name: Remotifier
startup: postworld
url: http://blockface.org/
softdepend: [Votifier]
version: '1.0'
commands:
    reward:
        usage: /reward <player>
        description: Inserts row into table.