name: Remotifier
version: ${build.number}
description: Get notified (aka votified) when a vote is made on a Minecraft server list for one or multiple servers.
authors: [Betterverse, SwearWord]
website: http://www.betterverse.net

main: net.betterverse.remotifier.Remotifier
softdepend: [Votifier]
startup: postworld
database: false

commands:
    reward:
        usage: /reward <player>
        description: Inserts row into table.
